# Site settings
title: دانشگاه علم و صنعت ایران
course_name: سیگنال‌ها و سیستم‌ها
course_description: درباره درس
course_semester: "بهار 1398"
description: |
    Instructor: محمد رضا محمدی

message: 
baseurl: "/signals_and_systems/3972"
url: "https://mrmohammadi.github.io/" # the base hostname & protocol for your site
githubdir: "mrmohammadi/mrmohammadi.github.io"

# Author/user information
email: mrmohammadi@iust.ac.ir
twitter_username: Mohammadi_IUST 
github_username:  mrmohammadi
authorurl: "http://webpages.iust.ac.ir/mrmohammadi/"
address: |
    ایران، تهران، دانشگاه علم و صنعت ایران، دانشکده مهندسی کامپیوتر


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css', '_js', '_fonts']
exclude: ['develop', 'build.sh']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    practical:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"



plugins_dir:
    - jekyll-jalali
