# Site settings
title: Iran University of Science and Technology (IUST)
course_name: Computer Vision
course_description: 
course_semester: "Fall 1399 (2020)"
description: |
    Instructor: Mohammad Reza Mohammadi

message: 
baseurl: "/computer_vision/3991"
url: "https://mrmohammadi.github.io/" # the base hostname & protocol for your site
githubdir: "mrmohammadi/mrmohammadi.github.io"

# Author/user information
email: mrmohammadi@iust.ac.ir
twitter_username: Mohammadi_IUST 
github_username:  mrmohammadi
authorurl: "http://webpages.iust.ac.ir/mrmohammadi/"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css', '_js']
exclude: ['develop', 'build.sh']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    practical:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"



plugins_dir:
    - jekyll-jalali
